### ISSUE TITLE
Замечания по коду

### ISSUE THREAD

**Issue by sergey-shambir** [knyazsergei/lab7#1]
- объявлять переменную PI излишне, см. http://stackoverflow.com/questions/6563810/m-pi-works-with-math-h-but-not-with-cmath-in-visual-studio
- в функцию time() надо передавать nullptr, а не 0 (стиль C++11)
- функцию getPoint следовало бы назвать по существу совершаемой ей работы. По существу функция переводит точку из полярной системы координат в декартову. Английские названия этих терминов можно найти по ссылкам на англ. вики из русских статей википедии.
- функция events принимает много параметров, следует использовать структуры для уменьшения их числа
- функция main слишком большая, содержит магические числа вместо именованных констант и неиспользуемые переменные, такие как intToStr.

**Comment by sergey-shambir** [comment]
- нет смысла сокращать название функции creatBg
- магические числа в коде: цвета, ширина, радиус и так далее. Нужны именованные константы.
- не надо выделать память через вызов creatBg прямо в структуре vectorObjects, такой подход очень опасный - при любом создании переменной выделяется память, которую потом можно забыть удалить. Лучше сдалать функцию initVectorObjects либо функцию init внутри структуры, и там выделять память. И чистить её через вызов функции destroy().
- в функции drawNumbers нет смысла объявлять i до цикла, магическое число 12 тоже не катит.
- в функции main надо навести порядок - есть лишние переменные

**Comment by sergey-shambir** [comment]
- Именование глобальных констант совпадает с именованием переменных. Такого быть не должно, глобальные константы должны иметь собственный стиль именования - обычно ```GLOBAL_CONSTANT```
- Все глобальные константы (да и переменные) должны иметь спецификатор static, чтобы не провоцировать ошибки компоновщика

**Comment by knyazsergei** [comment]
Замечания учел
